/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'date' : string,
  'name' : string,
  'time' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'sessionID' : bigint,
  'phone' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface CreateBookingRequestArgs {
  'date' : string,
  'name' : string,
  'time' : string,
  'email' : string,
  'message' : string,
  'sessionID' : bigint,
  'phone' : string,
}
export interface CreateSessionArgs {
  'name' : string,
  'description' : string,
  'iconName' : string,
  'durationMinutes' : bigint,
  'priceUSD' : bigint,
}
export interface SessionType {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'iconName' : string,
  'durationMinutes' : bigint,
  'priceUSD' : bigint,
}
export interface SiteSettings {
  'instagramHandle' : string,
  'phoneNumber' : string,
}
export interface Testimonial {
  'customerName' : string,
  'starRating' : bigint,
  'avatarInitials' : string,
  'testimonialText' : string,
}
export type Time = bigint;
export interface UpdateSettingsArgs {
  'instagramHandle' : string,
  'phoneNumber' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBookingRequest' : ActorMethod<
    [CreateBookingRequestArgs],
    { 'missingFields' : string } |
      { 'sessionTypeNotFound' : null } |
      { 'success' : { 'bookingID' : bigint } }
  >,
  'createSessionType' : ActorMethod<
    [CreateSessionArgs],
    { 'missingFields' : string } |
      { 'success' : { 'sessionID' : bigint } }
  >,
  'deleteSessionType' : ActorMethod<
    [bigint],
    { 'sessionTypeNotFound' : null } |
      { 'success' : null }
  >,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSessionType' : ActorMethod<[bigint], [] | [SessionType]>,
  'getSessionTypes' : ActorMethod<[], Array<SessionType>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTimeSlots' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedBackupTestimonials' : ActorMethod<[], undefined>,
  'updateBookingStatus' : ActorMethod<
    [bigint, BookingStatus],
    { 'success' : null } |
      { 'bookingNotFound' : null }
  >,
  'updateSessionType' : ActorMethod<
    [bigint, CreateSessionArgs],
    { 'missingFields' : string } |
      { 'sessionTypeNotFound' : null } |
      { 'success' : null }
  >,
  'updateSiteSettings' : ActorMethod<
    [UpdateSettingsArgs],
    { 'missingFields' : string } |
      { 'success' : null }
  >,
  'updateTimeSlots' : ActorMethod<[Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];