/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateBookingRequestArgs = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'sessionID' : IDL.Nat,
  'phone' : IDL.Text,
});
export const CreateSessionArgs = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'priceUSD' : IDL.Nat,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'sessionID' : IDL.Nat,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SessionType = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'priceUSD' : IDL.Nat,
});
export const SiteSettings = IDL.Record({
  'instagramHandle' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'customerName' : IDL.Text,
  'starRating' : IDL.Nat,
  'avatarInitials' : IDL.Text,
  'testimonialText' : IDL.Text,
});
export const UpdateSettingsArgs = IDL.Record({
  'instagramHandle' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBookingRequest' : IDL.Func(
      [CreateBookingRequestArgs],
      [
        IDL.Variant({
          'missingFields' : IDL.Text,
          'sessionTypeNotFound' : IDL.Null,
          'success' : IDL.Record({ 'bookingID' : IDL.Nat }),
        }),
      ],
      [],
    ),
  'createSessionType' : IDL.Func(
      [CreateSessionArgs],
      [
        IDL.Variant({
          'missingFields' : IDL.Text,
          'success' : IDL.Record({ 'sessionID' : IDL.Nat }),
        }),
      ],
      [],
    ),
  'deleteSessionType' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'sessionTypeNotFound' : IDL.Null, 'success' : IDL.Null })],
      [],
    ),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSessionType' : IDL.Func([IDL.Nat], [IDL.Opt(SessionType)], ['query']),
  'getSessionTypes' : IDL.Func([], [IDL.Vec(SessionType)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTimeSlots' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedBackupTestimonials' : IDL.Func([], [], []),
  'updateBookingStatus' : IDL.Func(
      [IDL.Nat, BookingStatus],
      [IDL.Variant({ 'success' : IDL.Null, 'bookingNotFound' : IDL.Null })],
      [],
    ),
  'updateSessionType' : IDL.Func(
      [IDL.Nat, CreateSessionArgs],
      [
        IDL.Variant({
          'missingFields' : IDL.Text,
          'sessionTypeNotFound' : IDL.Null,
          'success' : IDL.Null,
        }),
      ],
      [],
    ),
  'updateSiteSettings' : IDL.Func(
      [UpdateSettingsArgs],
      [IDL.Variant({ 'missingFields' : IDL.Text, 'success' : IDL.Null })],
      [],
    ),
  'updateTimeSlots' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateBookingRequestArgs = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'sessionID' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const CreateSessionArgs = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'priceUSD' : IDL.Nat,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'sessionID' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SessionType = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'priceUSD' : IDL.Nat,
  });
  const SiteSettings = IDL.Record({
    'instagramHandle' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'customerName' : IDL.Text,
    'starRating' : IDL.Nat,
    'avatarInitials' : IDL.Text,
    'testimonialText' : IDL.Text,
  });
  const UpdateSettingsArgs = IDL.Record({
    'instagramHandle' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBookingRequest' : IDL.Func(
        [CreateBookingRequestArgs],
        [
          IDL.Variant({
            'missingFields' : IDL.Text,
            'sessionTypeNotFound' : IDL.Null,
            'success' : IDL.Record({ 'bookingID' : IDL.Nat }),
          }),
        ],
        [],
      ),
    'createSessionType' : IDL.Func(
        [CreateSessionArgs],
        [
          IDL.Variant({
            'missingFields' : IDL.Text,
            'success' : IDL.Record({ 'sessionID' : IDL.Nat }),
          }),
        ],
        [],
      ),
    'deleteSessionType' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'sessionTypeNotFound' : IDL.Null,
            'success' : IDL.Null,
          }),
        ],
        [],
      ),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSessionType' : IDL.Func([IDL.Nat], [IDL.Opt(SessionType)], ['query']),
    'getSessionTypes' : IDL.Func([], [IDL.Vec(SessionType)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTimeSlots' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedBackupTestimonials' : IDL.Func([], [], []),
    'updateBookingStatus' : IDL.Func(
        [IDL.Nat, BookingStatus],
        [IDL.Variant({ 'success' : IDL.Null, 'bookingNotFound' : IDL.Null })],
        [],
      ),
    'updateSessionType' : IDL.Func(
        [IDL.Nat, CreateSessionArgs],
        [
          IDL.Variant({
            'missingFields' : IDL.Text,
            'sessionTypeNotFound' : IDL.Null,
            'success' : IDL.Null,
          }),
        ],
        [],
      ),
    'updateSiteSettings' : IDL.Func(
        [UpdateSettingsArgs],
        [IDL.Variant({ 'missingFields' : IDL.Text, 'success' : IDL.Null })],
        [],
      ),
    'updateTimeSlots' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };