/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Testimonial {
    customerName: string;
    starRating: bigint;
    avatarInitials: string;
    testimonialText: string;
}
export interface SiteSettings {
    instagramHandle: string;
    phoneNumber: string;
}
export type Time = bigint;
export interface CreateSessionArgs {
    name: string;
    description: string;
    iconName: string;
    durationMinutes: bigint;
    priceUSD: bigint;
}
export interface UpdateSettingsArgs {
    instagramHandle: string;
    phoneNumber: string;
}
export interface CreateBookingRequestArgs {
    date: string;
    name: string;
    time: string;
    email: string;
    message: string;
    sessionID: bigint;
    phone: string;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    date: string;
    name: string;
    time: string;
    email: string;
    message: string;
    timestamp: Time;
    sessionID: bigint;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export interface SessionType {
    id: bigint;
    name: string;
    description: string;
    iconName: string;
    durationMinutes: bigint;
    priceUSD: bigint;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_sessionTypeNotFound_success {
    sessionTypeNotFound = "sessionTypeNotFound",
    success = "success"
}
export enum Variant_success_bookingNotFound {
    success = "success",
    bookingNotFound = "bookingNotFound"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBookingRequest(args: CreateBookingRequestArgs): Promise<{
        __kind__: "missingFields";
        missingFields: string;
    } | {
        __kind__: "sessionTypeNotFound";
        sessionTypeNotFound: null;
    } | {
        __kind__: "success";
        success: {
            bookingID: bigint;
        };
    }>;
    createSessionType(args: CreateSessionArgs): Promise<{
        __kind__: "missingFields";
        missingFields: string;
    } | {
        __kind__: "success";
        success: {
            sessionID: bigint;
        };
    }>;
    deleteSessionType(sessionID: bigint): Promise<Variant_sessionTypeNotFound_success>;
    getBookings(): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getSessionType(sessionID: bigint): Promise<SessionType | null>;
    getSessionTypes(): Promise<Array<SessionType>>;
    getSiteSettings(): Promise<SiteSettings>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getTimeSlots(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedBackupTestimonials(): Promise<void>;
    updateBookingStatus(bookingID: bigint, newStatus: BookingStatus): Promise<Variant_success_bookingNotFound>;
    updateSessionType(sessionID: bigint, args: CreateSessionArgs): Promise<{
        __kind__: "missingFields";
        missingFields: string;
    } | {
        __kind__: "sessionTypeNotFound";
        sessionTypeNotFound: null;
    } | {
        __kind__: "success";
        success: null;
    }>;
    updateSiteSettings(args: UpdateSettingsArgs): Promise<{
        __kind__: "missingFields";
        missingFields: string;
    } | {
        __kind__: "success";
        success: null;
    }>;
    updateTimeSlots(newTimeSlots: Array<string>): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, SessionType as _SessionType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBookingRequest(arg0: CreateBookingRequestArgs): Promise<{
        __kind__: "missingFields";
        missingFields: string;
    } | {
        __kind__: "sessionTypeNotFound";
        sessionTypeNotFound: null;
    } | {
        __kind__: "success";
        success: {
            bookingID: bigint;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createBookingRequest(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBookingRequest(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSessionType(arg0: CreateSessionArgs): Promise<{
        __kind__: "missingFields";
        missingFields: string;
    } | {
        __kind__: "success";
        success: {
            sessionID: bigint;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createSessionType(arg0);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSessionType(arg0);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSessionType(arg0: bigint): Promise<Variant_sessionTypeNotFound_success> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSessionType(arg0);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSessionType(arg0);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionType(arg0: bigint): Promise<SessionType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionType(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionType(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionTypes(): Promise<Array<SessionType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionTypes();
            return result;
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return result;
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getTimeSlots(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimeSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimeSlots();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedBackupTestimonials(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedBackupTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedBackupTestimonials();
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<Variant_success_bookingNotFound> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSessionType(arg0: bigint, arg1: CreateSessionArgs): Promise<{
        __kind__: "missingFields";
        missingFields: string;
    } | {
        __kind__: "sessionTypeNotFound";
        sessionTypeNotFound: null;
    } | {
        __kind__: "success";
        success: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSessionType(arg0, arg1);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSessionType(arg0, arg1);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSiteSettings(arg0: UpdateSettingsArgs): Promise<{
        __kind__: "missingFields";
        missingFields: string;
    } | {
        __kind__: "success";
        success: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteSettings(arg0);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteSettings(arg0);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTimeSlots(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimeSlots(arg0);
            return result;
        }
    }
}
function from_candid_BookingStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionType]): SessionType | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    date: string;
    name: string;
    time: string;
    email: string;
    message: string;
    timestamp: _Time;
    sessionID: bigint;
    phone: string;
}): {
    id: bigint;
    status: BookingStatus;
    date: string;
    name: string;
    time: string;
    email: string;
    message: string;
    timestamp: Time;
    sessionID: bigint;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n9(_uploadFile, _downloadFile, value.status),
        date: value.date,
        name: value.name,
        time: value.time,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        sessionID: value.sessionID,
        phone: value.phone
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: null;
} | {
    bookingNotFound: null;
}): Variant_success_bookingNotFound {
    return "success" in value ? Variant_success_bookingNotFound.success : "bookingNotFound" in value ? Variant_success_bookingNotFound.bookingNotFound : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    missingFields: string;
} | {
    sessionTypeNotFound: null;
} | {
    success: null;
}): {
    __kind__: "missingFields";
    missingFields: string;
} | {
    __kind__: "sessionTypeNotFound";
    sessionTypeNotFound: null;
} | {
    __kind__: "success";
    success: null;
} {
    return "missingFields" in value ? {
        __kind__: "missingFields",
        missingFields: value.missingFields
    } : "sessionTypeNotFound" in value ? {
        __kind__: "sessionTypeNotFound",
        sessionTypeNotFound: value.sessionTypeNotFound
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    missingFields: string;
} | {
    success: null;
}): {
    __kind__: "missingFields";
    missingFields: string;
} | {
    __kind__: "success";
    success: null;
} {
    return "missingFields" in value ? {
        __kind__: "missingFields",
        missingFields: value.missingFields
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    missingFields: string;
} | {
    sessionTypeNotFound: null;
} | {
    success: {
        bookingID: bigint;
    };
}): {
    __kind__: "missingFields";
    missingFields: string;
} | {
    __kind__: "sessionTypeNotFound";
    sessionTypeNotFound: null;
} | {
    __kind__: "success";
    success: {
        bookingID: bigint;
    };
} {
    return "missingFields" in value ? {
        __kind__: "missingFields",
        missingFields: value.missingFields
    } : "sessionTypeNotFound" in value ? {
        __kind__: "sessionTypeNotFound",
        sessionTypeNotFound: value.sessionTypeNotFound
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    missingFields: string;
} | {
    success: {
        sessionID: bigint;
    };
}): {
    __kind__: "missingFields";
    missingFields: string;
} | {
    __kind__: "success";
    success: {
        sessionID: bigint;
    };
} {
    return "missingFields" in value ? {
        __kind__: "missingFields",
        missingFields: value.missingFields
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sessionTypeNotFound: null;
} | {
    success: null;
}): Variant_sessionTypeNotFound_success {
    return "sessionTypeNotFound" in value ? Variant_sessionTypeNotFound_success.sessionTypeNotFound : "success" in value ? Variant_sessionTypeNotFound_success.success : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
